-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 28, 2021 at 06:16 PM
-- Server version: 10.4.20-MariaDB
-- PHP Version: 7.3.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `task-sveltetech`
--

-- --------------------------------------------------------

--
-- Table structure for table `movies`
--

CREATE TABLE `movies` (
  `id` int(11) NOT NULL,
  `year` int(11) DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `directors` varchar(200) DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `plot` varchar(255) DEFAULT NULL,
  `release_date` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `movies`
--

INSERT INTO `movies` (`id`, `year`, `title`, `directors`, `image_url`, `plot`, `release_date`) VALUES
(1, 2013, 'Rush', 'Ron Howard', 'http://ia.media-imdb.com/images/M/MV5BMTQyMDE0MTY0OV5BMl5BanBnXkFtZTcwMjI2OTI0OQ@@._V1_SX400_.jpg', 'A re-creation of the merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.', '2013-09-02 00:00:00'),
(2, 2013, 'Prisoners', 'Denis Villeneuve', 'http://ia.media-imdb.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_SX400_.jpg', 'When Keller Dover\'s daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts. But just how far will this desperate father go to protect his family?', '2013-08-30 00:00:00'),
(3, 2013, 'Thor: The Dark World', 'Alan Taylor', 'http://ia.media-imdb.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_SX400_.jpg', 'Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.', '2013-10-30 00:00:00'),
(4, 2013, 'The Hunger Games: Catching Fire', 'Francis Lawrence', 'http://ia.media-imdb.com/images/M/MV5BMTAyMjQ3OTAxMzNeQTJeQWpwZ15BbWU4MDU0NzA1MzAx._V1_SX400_.jpg', 'Katniss Everdeen and Peeta Mellark become targets of the Capitol after their victory in the 74th Hunger Games sparks a rebellion in the Districts of Panem.', '2013-11-11 00:00:00'),
(5, 2013, 'This Is the End', 'Evan Goldberg', 'http://ia.media-imdb.com/images/M/MV5BMTQxODE3NjM1Ml5BMl5BanBnXkFtZTcwMzkzNjc4OA@@._V1_SX400_.jpg', 'While attending a party at James Franco\'s house, Seth Rogen, Jay Baruchel and many other celebrities are faced with the apocalypse.', '2013-06-03 00:00:00'),
(6, 2013, 'Insidious: Chapter 2', 'James Wan', 'http://ia.media-imdb.com/images/M/MV5BMTg0OTA5ODIxNF5BMl5BanBnXkFtZTcwNTUzNDg4OQ@@._V1_SX400_.jpg', 'The haunted Lambert family seeks to uncover the mysterious childhood secret that has left them dangerously connected to the spirit world.', '2013-09-13 00:00:00'),
(7, 2013, 'World War Z', 'Marc Forster', 'http://ia.media-imdb.com/images/M/MV5BMTg0NTgxMjIxOF5BMl5BanBnXkFtZTcwMDM0MDY1OQ@@._V1_SX400_.jpg', 'United Nations employee Gerry Lane traverses the world in a race against time to stop the Zombie pandemic that is toppling armies and governments, and threatening to destroy humanity itself.', '2013-06-02 00:00:00'),
(8, 2014, 'X-Men: Days of Future Past', 'Bryan Singer', 'http://ia.media-imdb.com/images/M/MV5BMTQ0NzIwNTA1MV5BMl5BanBnXkFtZTgwNjY2OTcwMDE@._V1_SX400_.jpg', 'The X-Men send Wolverine to the past to change a major historical event that could globally impact man and mutant kind.', '2014-05-21 00:00:00'),
(9, 2014, 'Transformers: Age of Extinction', 'Michael Bay', 'http://ia.media-imdb.com/images/M/MV5BMTQyMDA5Nzg0Nl5BMl5BanBnXkFtZTgwNzA4NDcxMDE@._V1_SX400_.jpg', 'A mechanic and his daughter make a discovery that brings down Autobots and Decepticons - and a paranoid government official - on them.', '2014-06-25 00:00:00'),
(10, 2013, 'Now You See Me', 'Louis Leterrier', 'http://ia.media-imdb.com/images/M/MV5BMTY0NDY3MDMxN15BMl5BanBnXkFtZTcwOTM5NzMzOQ@@._V1_SX400_.jpg', 'An FBI agent and an Interpol detective track a team of illusionists who pull off bank heists during their performances and reward their audiences with the money.', '2013-05-21 00:00:00'),
(11, 2013, 'Gravity', 'Alfonso Cuaron', 'http://ia.media-imdb.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_SX400_.jpg', 'A medical engineer and an astronaut work together to survive after an accident leaves them adrift in space.', '2013-08-28 00:00:00'),
(12, 2013, 'We\'re the Millers', 'Rawson Marshall Thurber', 'http://ia.media-imdb.com/images/M/MV5BMjA5Njc0NDUxNV5BMl5BanBnXkFtZTcwMjYzNzU1OQ@@._V1_SX400_.jpg', 'A veteran pot dealer creates a fake family as part of his plan to move a huge shipment of weed into the U.S. from Mexico.', '2013-08-03 00:00:00'),
(13, 2013, 'Riddick', 'David Twohy', 'http://ia.media-imdb.com/images/M/MV5BMTk5NzYwMzQ4MV5BMl5BanBnXkFtZTcwMjE5MTI1OQ@@._V1_SX400_.jpg', 'Left for dead on a sun-scorched planet, Riddick finds himself up against an alien race of predators. Activating an emergency beacon alerts two ships: one carrying a new breed of mercenary, the other captained by a man from Riddick\'s past.', '2013-09-04 00:00:00'),
(14, 2013, 'The Family', 'Luc Besson', 'http://ia.media-imdb.com/images/M/MV5BMjE2MzI0MzkyNV5BMl5BanBnXkFtZTcwMjQ2MDM2OQ@@._V1_SX400_.jpg', 'The Manzoni family, a notorious mafia clan, is relocated to Normandy, France under the witness protection program, where fitting in soon becomes challenging as their old habits die hard.', '2013-09-10 00:00:00'),
(15, 2013, 'Star Trek Into Darkness', 'J.J. Abrams', 'http://ia.media-imdb.com/images/M/MV5BMTk2NzczOTgxNF5BMl5BanBnXkFtZTcwODQ5ODczOQ@@._V1_SX400_.jpg', 'After the crew of the Enterprise find an unstoppable force of terror from within their own organization, Captain Kirk leads a manhunt to a war-zone world to capture a one man weapon of mass destruction.', '2013-05-02 00:00:00'),
(16, 2013, 'After Earth', 'M. Night Shyamalan', 'http://ia.media-imdb.com/images/M/MV5BMTY3MzQyMjkwMl5BMl5BanBnXkFtZTcwMDk2OTE0OQ@@._V1_SX400_.jpg', 'A crash landing leaves Kitai Raige and his father Cypher stranded on Earth, a millennium after events forced humanity\'s escape. With Cypher injured, Kitai must embark on a perilous journey to signal for help.', '2013-05-01 00:00:00'),
(17, 2013, 'The Great Gatsby', 'Baz Luhrmann', 'http://ia.media-imdb.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_SX400_.jpg', 'A Midwestern war veteran finds himself drawn to the past and lifestyle of his millionaire neighbor.', '2013-05-01 00:00:00'),
(18, 2014, 'Divergent', 'Neil Burger', 'http://ia.media-imdb.com/images/M/MV5BMjIyOTEyODQ4OV5BMl5BanBnXkFtZTgwMDIwNzEzMDE@._V1_SX400_.jpg', 'Beatrice Prior, a teenager with a special mind, finds her life threatened when an authoritarian leader seeks to exterminate her kind in her effort to seize control of their divided society.', '2014-03-20 00:00:00'),
(19, 2013, 'We Are What We Are', 'Jim Mickle', 'http://ia.media-imdb.com/images/M/MV5BMjI3NjI3NjAyN15BMl5BanBnXkFtZTgwODE3NzMxMDE@._V1_SX400_.jpg', 'The Parkers, a reclusive family who follow ancient customs, find their secret existence threatened as a torrential downpour moves into their area, forcing daughters Iris and Rose to assume responsibilities beyond those of a typical family.', '2013-01-18 00:00:00'),
(20, 2013, 'Iron Man 3', 'Shane Black', 'http://ia.media-imdb.com/images/M/MV5BMjIzMzAzMjQyM15BMl5BanBnXkFtZTcwNzM2NjcyOQ@@._V1_SX400_.jpg', 'When Tony Stark\'s world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.', '2013-04-18 00:00:00'),
(21, 2014, 'The Amazing Spider-Man 2', 'Marc Webb', 'http://ia.media-imdb.com/images/M/MV5BMjE0MDAwNTUzNF5BMl5BanBnXkFtZTcwNDQ4NDYxOQ@@._V1_SX400_.jpg', 'Spider-Man squares off against the Rhino and the powerful Electro while struggling to keep his promise to leave Gwen Stacey out of his dangerous life.', '2014-04-17 00:00:00'),
(22, 2013, 'Curse of Chucky', 'Don Mancini', 'http://ia.media-imdb.com/images/M/MV5BMjkxMjM0MDE3OF5BMl5BanBnXkFtZTcwMDQ3NzI4OQ@@._V1_SX400_.jpg', 'After her mother\'s mysterious death, Nica begins to suspect that the talking, red-haired doll her visiting niece has been playing with may be the key to recent bloodshed and chaos.', '2013-08-02 00:00:00'),
(23, 2013, 'The Conjuring', 'James Wan', 'http://ia.media-imdb.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX400_.jpg', 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.', '2013-06-08 00:00:00'),
(24, 2013, 'Oldboy', 'Spike Lee', 'http://ia.media-imdb.com/images/M/MV5BMTk5NTEwMzI5OV5BMl5BanBnXkFtZTgwMDQ4ODUwMDE@._V1_SX400_.jpg', 'Obsessed with vengeance, a man sets out to find out why he was kidnapped and locked up into solitary confinement for 20 years without reason.', '2013-10-10 00:00:00'),
(25, 2013, 'Escape Plan', 'Mikael Hafstrom', 'http://ia.media-imdb.com/images/M/MV5BMTk3OTcxMTEyNl5BMl5BanBnXkFtZTcwMDQ4MjQ2OQ@@._V1_SX400_.jpg', 'When a structural-security authority finds himself incarcerated in a prison he designed, he has to put his skills to escape and find out who framed him.', '2013-07-18 00:00:00'),
(26, 2013, 'Elysium', 'Neill Blomkamp', 'http://ia.media-imdb.com/images/M/MV5BNDc2NjU0MTcwNV5BMl5BanBnXkFtZTcwMjg4MDg2OQ@@._V1_SX400_.jpg', 'Set in the year 2154, where the very wealthy live on a man-made space station while the rest of the population resides on a ruined Earth, a man takes on a mission that could bring equality to the polarized worlds.', '2013-08-07 00:00:00'),
(27, 2013, 'Cloudy with a Chance of Meatballs 2', 'Cody Cameron', 'http://ia.media-imdb.com/images/M/MV5BMTYzNDM0MDI1NF5BMl5BanBnXkFtZTcwNzQ5NzYxOQ@@._V1_SX400_.jpg', 'Flint Lockwood now works at The Live Corp Company for his idol Chester V. But he\'s forced to leave his post when he learns that his most infamous machine is still operational and is churning out menacing food-animal hybrids.', '2013-09-26 00:00:00'),
(28, 2014, 'RoboCop', 'Jose Padilha', 'http://ia.media-imdb.com/images/M/MV5BMjMwNzQ2MDkyOV5BMl5BanBnXkFtZTgwMjE5MjMyMDE@._V1_SX400_.jpg', 'In 2028 Detroit, when Alex Murphy (Joel Kinnaman) - a loving husband, father and good cop - is critically injured in the line of duty, the multinational conglomerate OmniCorp sees their chance for a part-man, part-robot police officer.', '2014-01-30 00:00:00'),
(29, 2013, 'Carrie', 'Kimberly Peirce', 'http://ia.media-imdb.com/images/M/MV5BMTc1MDIyOTkxN15BMl5BanBnXkFtZTgwMTU1NzEzMDE@._V1_SX400_.jpg', 'A reimagining of the classic horror tale about Carrie White, a shy girl outcast by her peers and sheltered by her deeply religious mother, who unleashes telekinetic terror on her small town after being pushed too far at her senior prom.', '2013-10-07 00:00:00'),
(30, 2013, 'The Mortal Instruments: City of Bones', 'Harald Zwart', 'http://ia.media-imdb.com/images/M/MV5BMTc5NzAyOTQyNF5BMl5BanBnXkFtZTcwNzQ1MDc4OQ@@._V1_SX400_.jpg', 'When her mother disappears, Clary Fray learns that she descends from a line of warriors who protect our world from demons. She joins forces with others like her and heads into a dangerous alternate New York called Downworld.', '2013-08-12 00:00:00'),
(31, 2014, 'Captain America: The Winter Soldier', 'Anthony Russo', 'http://ia.media-imdb.com/images/M/MV5BMjAzMTg3MDcxM15BMl5BanBnXkFtZTcwNDQzNzI4OQ@@._V1_SX400_.jpg', 'Steve Rogers struggles to embrace his role in the modern world and teams up with Natasha Romanoff, aka Black Widow, to battle a powerful yet shadowy enemy in present-day Washington, D.C.', '2014-04-02 00:00:00'),
(32, 2014, 'Need for Speed', 'Scott Waugh', 'http://ia.media-imdb.com/images/M/MV5BMjU2MTM3OTA3N15BMl5BanBnXkFtZTgwMjQ5MDYyMDE@._V1_SX400_.jpg', 'Fresh from prison, a street racer who was framed by a wealthy business associate joins a cross country race with revenge in mind. His ex-partner, learning of the plan, places a massive bounty on his head as the race begins.', '2014-03-13 00:00:00'),
(33, 2013, 'Runner Runner', 'Brad Furman', 'http://ia.media-imdb.com/images/M/MV5BMTU5OTA0MjI4Ml5BMl5BanBnXkFtZTgwMTgxOTQwMDE@._V1_SX400_.jpg', 'When a poor college student who cracks an online poker game goes bust, he arranges a face-to-face with the man he thinks cheated him, a sly offshore entrepreneur.', '2013-09-25 00:00:00'),
(34, 2013, 'I Spit on Your Grave 2', 'Steven R. Monroe', 'http://ia.media-imdb.com/images/M/MV5BMTc1Nzk3NjM0M15BMl5BanBnXkFtZTgwMjM5MzYyMDE@._V1_SX400_.jpg', NULL, '2013-08-25 00:00:00'),
(35, 2013, 'Battle of the Year', 'Benson Lee', 'http://ia.media-imdb.com/images/M/MV5BOTY2OTcyNzM3NF5BMl5BanBnXkFtZTgwNzgxMjkxMDE@._V1_SX400_.jpg', 'Battle of the Year attracts all the best teams from around the world, but the Americans haven\'t won in fifteen years. Dante enlists Blake to assemble a team of the best dancers and bring the Trophy back to America where it started.', '2013-09-19 00:00:00'),
(36, 2013, 'Behind the Candelabra', 'Steven Soderbergh', 'http://ia.media-imdb.com/images/M/MV5BMTg0OTY2OTM0OF5BMl5BanBnXkFtZTcwMTk4OTQ1OQ@@._V1_SX400_.jpg', 'Based on the autobiographical novel, the tempestuous 6-year relationship between Liberace and his (much younger) lover, Scott Thorson, is recounted.', '2013-05-21 00:00:00'),
(37, 2013, 'No se Aceptan Devoluciones', 'Eugenio Derbez', 'http://ia.media-imdb.com/images/M/MV5BMTUyNjI3ODI0N15BMl5BanBnXkFtZTcwMTQ1NTY5OQ@@._V1_SX400_.jpg', 'A man who has made a new life for himself and the daughter left on his doorstep 6 years ago finds his family threatened when the birth mother resurfaces.', '2013-08-30 00:00:00'),
(38, 2013, 'The Bling Ring', 'Sofia Coppola', 'http://ia.media-imdb.com/images/M/MV5BMTQzMTgwMzQxN15BMl5BanBnXkFtZTcwOTcwNTY0OQ@@._V1_SX400_.jpg', 'Inspired by actual events, a group of fame-obsessed teenagers use the internet to track celebrities\' whereabouts in order to rob their homes.', '2013-05-16 00:00:00'),
(39, 2013, 'Furious 6', 'Justin Lin', 'http://ia.media-imdb.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_SX400_.jpg', 'Hobbs has Dom and Brian reassemble their crew in order to take down a mastermind who commands an organization of mercenary drivers across 12 countries. Payment? Full pardons for them all.', '2013-05-07 00:00:00'),
(40, 2013, 'Machete Kills', 'Robert Rodriguez', 'http://ia.media-imdb.com/images/M/MV5BMjA2MzUxMTM3M15BMl5BanBnXkFtZTgwMzA2NzkxMDE@._V1_SX400_.jpg', 'The U.S. government recruits Machete to battle his way through Mexico in order to take down an arms dealer who looks to launch a weapon into space.', '2013-09-19 00:00:00'),
(41, 2013, '12 Years a Slave', 'Steve McQueen', 'http://ia.media-imdb.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_SX400_.jpg', 'In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.', '2013-08-30 00:00:00'),
(42, 2013, 'The World\'s End', 'Edgar Wright', 'http://ia.media-imdb.com/images/M/MV5BNzA1MTk1MzY0OV5BMl5BanBnXkFtZTgwNjkzNTUwMDE@._V1_SX400_.jpg', 'Five friends who reunite in an attempt to top their epic pub crawl from 20 years earlier unwittingly become humankind\'s only hope for survival.', '2013-07-18 00:00:00'),
(43, 2012, 'Pitch Perfect', 'Jason Moore', 'http://ia.media-imdb.com/images/M/MV5BMTcyMTMzNzE5N15BMl5BanBnXkFtZTcwNzg5NjM5Nw@@._V1_SX400_.jpg', 'Beca, a freshman at Barden University, is cajoled into joining The Bellas, her school\'s all-girls singing group. Injecting some much needed energy into their repertoire, The Bellas take on their male rivals in a campus competition.', '2012-09-28 00:00:00'),
(44, 2013, 'Epic', 'Chris Wedge', 'http://ia.media-imdb.com/images/M/MV5BMTgyNDYwNzE5NV5BMl5BanBnXkFtZTcwMzUyODM5OA@@._V1_SX400_.jpg', 'A teenager finds herself transported to a deep forest setting where a battle between the forces of good and the forces of evil is taking place. She bands together with a rag-tag group characters in order to save their world -- and ours.', '2013-05-15 00:00:00'),
(45, 2012, 'The Avengers', 'Joss Whedon', 'http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX400_.jpg', 'Nick Fury of S.H.I.E.L.D. assembles a team of superhumans to save the planet from Loki and his army.', '2012-04-11 00:00:00'),
(46, 2013, 'Metallica Through the Never', 'Nimrod Antal', 'http://ia.media-imdb.com/images/M/MV5BMjQwNjk5MTk4Ml5BMl5BanBnXkFtZTcwNTgwNDA5OQ@@._V1_SX400_.jpg', 'Trip, a young roadie for Metallica, is sent on an urgent mission during the band\'s show. But what seems like a simple assignment turns into a surreal adventure.', '2013-09-09 00:00:00'),
(47, 2013, 'Oblivion', 'Joseph Kosinski', 'http://ia.media-imdb.com/images/M/MV5BMTQwMDY0MTA4MF5BMl5BanBnXkFtZTcwNzI3MDgxOQ@@._V1_SX400_.jpg', 'A veteran assigned to extract Earth\'s remaining resources begins to question what he knows about his mission and himself.', '2013-04-10 00:00:00'),
(48, 2013, 'Dom Hemingway', 'Richard Shepard', 'http://ia.media-imdb.com/images/M/MV5BMTczMDYzOTAwM15BMl5BanBnXkFtZTgwMDg5OTgwMDE@._V1_SX400_.jpg', 'After spending 12 years in prison for keeping his mouth shut, notorious safe-cracker Dom Hemingway is back on the streets of London looking to collect what he\'s owed.', '2013-09-08 00:00:00'),
(49, 2013, 'The Hangover Part III', 'Todd Phillips', 'http://ia.media-imdb.com/images/M/MV5BMTA0NjE1MzMzODheQTJeQWpwZ15BbWU3MDY4MTQ3Mzk@._V1_SX400_.jpg', 'When one of their own is kidnapped by an angry gangster, the Wolf Pack must track down Mr. Chow, who has escaped from prison and is on the lam.', '2013-05-20 00:00:00'),
(50, 2013, 'Despicable Me 2', 'Pierre Coffin', 'http://ia.media-imdb.com/images/M/MV5BOTg4NTk2OTg5N15BMl5BanBnXkFtZTcwMDk1MzI2OQ@@._V1_SX400_.jpg', 'Gru is recruited by the Anti-Villain League to help deal with a powerful new super criminal.', '2013-06-16 00:00:00'),
(51, 2013, 'The Butler', 'Lee Daniels', 'http://ia.media-imdb.com/images/M/MV5BMjM2NDY3MjkyMF5BMl5BanBnXkFtZTcwMDM5Nzg5OQ@@._V1_SX400_.jpg', 'As Cecil Gaines serves eight presidents during his tenure as a butler at the White House, the civil rights movement, Vietnam, and other major events affect this man\'s life, family, and American society.', '2013-08-05 00:00:00'),
(52, 2014, 'Dumb and Dumber To', 'Bobby Farrelly', NULL, '20 years after the dimwits set out on their first adventure, they head out in search of one of their long lost children in the hope of gaining a new kidney.', '2014-01-01 00:00:00'),
(53, 2013, 'Blue Jasmine', 'Woody Allen', 'http://ia.media-imdb.com/images/M/MV5BMTc0ODk5MzEyMV5BMl5BanBnXkFtZTcwMzI0MDY1OQ@@._V1_SX400_.jpg', 'A New York socialite, deeply troubled and in denial, arrives in San Francisco to impose upon her sister. She looks a million, but isn\'t bringing money, peace, or love...', '2013-07-26 00:00:00'),
(54, 2013, 'Ender\'s Game', 'Gavin Hood', 'http://ia.media-imdb.com/images/M/MV5BMjAzMzI5OTgzMl5BMl5BanBnXkFtZTgwMTU5MTAwMDE@._V1_SX400_.jpg', '70 years after a horrific alien war, an unusually gifted child is sent to an advanced military school in space to prepare for a future invasion.', '2013-10-24 00:00:00'),
(55, 2013, 'White House Down', 'Roland Emmerich', 'http://ia.media-imdb.com/images/M/MV5BMTAyNzQyNTcwNjVeQTJeQWpwZ15BbWU3MDAwOTQ4Nzk@._V1_SX400_.jpg', 'While on a tour of the White House with his young daughter, a Capitol policeman springs into action to save his child and protect the president from a heavily armed group of paramilitary invaders.', '2013-06-26 00:00:00'),
(56, 2013, 'Pain & Gain', 'Michael Bay', 'http://ia.media-imdb.com/images/M/MV5BMTU0NDE5NTU0OV5BMl5BanBnXkFtZTcwMzI1OTMzOQ@@._V1_SX400_.jpg', 'A trio of bodybuilders in Florida get caught up in an extortion ring and a kidnapping scheme that goes terribly wrong.', '2013-04-11 00:00:00'),
(57, 2013, '2 Guns', 'Baltasar Kormakur', 'http://ia.media-imdb.com/images/M/MV5BNTQ5MTgzNDg4OF5BMl5BanBnXkFtZTcwMjAyODEzOQ@@._V1_SX400_.jpg', 'A DEA agent and a naval intelligence officer find themselves on the run after a botched attempt to infiltrate a drug cartel. While fleeing, they learn the secret of their shaky alliance: Neither knew that the other was an undercover agent.', '2013-07-30 00:00:00'),
(58, 2012, 'The Dark Knight Rises', 'Christopher Nolan', 'http://ia.media-imdb.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX400_.jpg', 'Eight years on, a new evil rises from where the Batman and Commissioner Gordon tried to bury it, causing the Batman to resurface and fight to protect Gotham City... the very city which brands him an enemy.', '2012-07-16 00:00:00'),
(59, 2012, 'The Place Beyond the Pines', 'Derek Cianfrance', 'http://ia.media-imdb.com/images/M/MV5BMjc1OTEwNjU4N15BMl5BanBnXkFtZTcwNzUzNDIwOQ@@._V1_SX400_.jpg', 'A motorcycle stunt rider turns to robbing banks as a way to provide for his lover and their newborn child, a decision that puts him on a collision course with an ambitious rookie cop navigating a department ruled by a corrupt detective.', '2012-09-07 00:00:00'),
(60, 2014, 'Fast & Furious 7', 'James Wan', NULL, 'After Dominic Toretto and his crew helped take down Owen Shaw, his brother Ian Shaw now wants revenge.', '2014-07-10 00:00:00'),
(61, 2013, 'jOBS', 'Joshua Michael Stern', 'http://ia.media-imdb.com/images/M/MV5BMTM5NTQ3MTYxN15BMl5BanBnXkFtZTcwODE2Nzk3OQ@@._V1_SX400_.jpg', 'The story of Steve Jobs\' ascension from college dropout into one of the most revered creative entrepreneurs of the 20th century.', '2013-01-25 00:00:00'),
(62, 2012, 'Disconnect', 'Henry Alex Rubin', 'http://ia.media-imdb.com/images/M/MV5BMjA2MTEzMDkyOF5BMl5BanBnXkFtZTcwNzc4NTgxOQ@@._V1_SX400_.jpg', 'A drama centered on a group of people searching for human connections in today\'s wired world.', '2012-09-11 00:00:00'),
(63, 2011, 'Bridesmaids', 'Paul Feig', 'http://ia.media-imdb.com/images/M/MV5BMjAyOTMyMzUxNl5BMl5BanBnXkFtZTcwODI4MzE0NA@@._V1_SX400_.jpg', 'Competition between the maid of honor and a bridesmaid, over who is the bride\'s best friend, threatens to upend the life of an out-of-work pastry chef.', '2011-04-28 00:00:00'),
(64, 2013, 'Man of Steel', 'Zack Snyder', 'http://ia.media-imdb.com/images/M/MV5BMjI5OTYzNjI0Ml5BMl5BanBnXkFtZTcwMzM1NDA1OQ@@._V1_SX400_.jpg', 'A young itinerant worker is forced to confront his secret extraterrestrial heritage when Earth is invaded by members of his race.', '2013-06-10 00:00:00'),
(65, 2013, 'Ghost Team One', 'Ben Peyser', 'http://ia.media-imdb.com/images/M/MV5BOTYwODQ3NzUyOV5BMl5BanBnXkFtZTgwNjAxNDcyMDE@._V1_SX400_.jpg', 'Two roommates deathly afraid of ghosts both fall in love with a girl who believes their home is haunted.', '2013-01-20 00:00:00'),
(66, 2010, 'Insidious', 'James Wan', 'http://ia.media-imdb.com/images/M/MV5BMTYyOTAxMDA0OF5BMl5BanBnXkFtZTcwNzgwNTc1NA@@._V1_SX400_.jpg', 'A family looks to prevent evil spirits from trapping their comatose child in a realm called The Further.', '2010-09-14 00:00:00'),
(67, 2014, 'Godzilla', 'Gareth Edwards', 'http://ia.media-imdb.com/images/M/MV5BMTk5MTUwNTY2Nl5BMl5BanBnXkFtZTcwMDk0MTk4OQ@@._V1_SX400_.jpg', 'A giant radioactive monster called Godzilla awakens from its slumber to wreak destruction on its creators.', '2014-05-14 00:00:00'),
(68, 2012, 'Wreck-It Ralph', 'Rich Moore', 'http://ia.media-imdb.com/images/M/MV5BNzMxNTExOTkyMF5BMl5BanBnXkFtZTcwMzEyNDc0OA@@._V1_SX400_.jpg', 'A video game villain wants to be a hero and sets out to fulfill his dream, but his quest brings havoc to the whole arcade where he lives.', '2012-11-01 00:00:00'),
(69, 2013, 'The Hobbit: The Desolation of Smaug', 'Peter Jackson', 'http://ia.media-imdb.com/images/M/MV5BMjAxMjMzMzAxOV5BMl5BanBnXkFtZTcwNTU3NzU2OQ@@._V1_SX400_.jpg', 'The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to get their gold back from the Dragon, Smaug.', '2013-12-11 00:00:00'),
(70, 2013, 'Frozen', 'Chris Buck', 'http://ia.media-imdb.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX400_.jpg', 'Fearless optimist Anna teams up with Kristoff in an epic journey, encountering Everest-like conditions, and a hilarious snowman named Olaf in a race to find Anna\'s sister Elsa, whose icy powers have trapped the kingdom in eternal winter.', '2013-11-20 00:00:00'),
(71, 2012, 'Spring Breakers', 'Harmony Korine', 'http://ia.media-imdb.com/images/M/MV5BNDE3MDQzMDA5OF5BMl5BanBnXkFtZTcwMTUxNTgxOQ@@._V1_SX400_.jpg', 'Four college girls who land in jail after robbing a restaurant in order to fund their spring break vacation find themselves bailed out by a drug and arms dealer who wants them to do some dirty work.', '2012-09-05 00:00:00'),
(72, 2012, 'Silver Linings Playbook', 'David O. Russell', 'http://ia.media-imdb.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_SX400_.jpg', 'After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.', '2012-09-08 00:00:00'),
(73, 2013, 'R.I.P.D.', 'Robert Schwentke', 'http://ia.media-imdb.com/images/M/MV5BMTM5OTYxNzE5N15BMl5BanBnXkFtZTcwMDU1MTQ4OQ@@._V1_SX400_.jpg', 'A recently slain cop joins a team of undead police officers working for the Rest in Peace Department and tries to find the man who murdered him.', '2013-07-17 00:00:00'),
(74, 1994, 'The Shawshank Redemption', 'Frank Darabont', 'http://ia.media-imdb.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SX400_.jpg', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', '1994-09-10 00:00:00'),
(75, 2014, 'Fifty Shades of Grey', 'Sam Taylor-Johnson', NULL, 'A literature student Anastasia Steele meets a handsome, yet tormented, billionaire named Christian Grey.', '2014-08-01 00:00:00'),
(76, 2013, 'Pacific Rim', 'Guillermo del Toro', 'http://ia.media-imdb.com/images/M/MV5BMTY3MTI5NjQ4Nl5BMl5BanBnXkFtZTcwOTU1OTU0OQ@@._V1_SX400_.jpg', 'As a war between humankind and monstrous sea creatures wages on, a former pilot and a trainee are paired up to drive a seemingly obsolete special weapon in a desperate effort to save the world from the apocalypse.', '2013-07-02 00:00:00'),
(77, 2012, 'The Hunger Games', 'Gary Ross', 'http://ia.media-imdb.com/images/M/MV5BMjA4NDg3NzYxMF5BMl5BanBnXkFtZTcwNTgyNzkyNw@@._V1_SX400_.jpg', 'Katniss Everdeen voluntarily takes her younger sister\'s place in the Hunger Games, a televised fight to the death in which two teenagers from each of the twelve Districts of Panem are chosen at random to compete.', '2012-03-12 00:00:00'),
(78, 2013, 'The Last Days on Mars', 'Ruairi Robinson', 'http://ia.media-imdb.com/images/M/MV5BMTk4ODgxMDU0M15BMl5BanBnXkFtZTgwOTg0NzcyMDE@._V1_SX400_.jpg', 'A group of astronaut explorers succumb one by one to a mysterious and terrifying force while collecting specimens on Mars.', '2013-05-20 00:00:00'),
(79, 2013, 'Baggage Claim', 'David E. Talbert', 'http://ia.media-imdb.com/images/M/MV5BMjIyNDU4NTY3M15BMl5BanBnXkFtZTcwOTA3MDA1OQ@@._V1_SX400_.jpg', 'Pledging to keep herself from being the oldest and the only woman in her entire family never to wed, Montana embarks on a thirty-day, thirty-thousand-mile expedition to charm a potential suitor into becoming her fiance.', '2013-09-27 00:00:00'),
(80, 2013, 'Percy Jackson: Sea of Monsters', 'Thor Freudenthal', 'http://ia.media-imdb.com/images/M/MV5BMTUwODUyODI0Nl5BMl5BanBnXkFtZTcwNzAxODY2OQ@@._V1_SX400_.jpg', 'In order to restore their dying safe haven, the son of Poseidon and his friends embark on a quest to the Sea of Monsters to find the mythical Golden Fleece while trying to stop an ancient evil from rising.', '2013-08-07 00:00:00'),
(81, 2012, 'Byzantium', 'Neil Jordan', 'http://ia.media-imdb.com/images/M/MV5BMTk2Nzc0NDQwMV5BMl5BanBnXkFtZTcwNjI2MjY3OQ@@._V1_SX400_.jpg', 'Residents of a coastal town learn, with deathly consequences, the secret shared by the two mysterious women who have sought shelter at a local resort.', '2012-09-09 00:00:00'),
(82, 2011, 'X-Men: First Class', 'Matthew Vaughn', 'http://ia.media-imdb.com/images/M/MV5BMTg5OTMxNzk4Nl5BMl5BanBnXkFtZTcwOTk1MjAwNQ@@._V1_SX400_.jpg', 'In 1962, the United States government enlists the help of Mutants with superhuman abilities to stop a malicious dictator who is determined to start world war III.', '2011-05-25 00:00:00'),
(83, 1993, 'Hocus Pocus', 'Kenny Ortega', 'http://ia.media-imdb.com/images/M/MV5BMTI3MDI2NDc3Ml5BMl5BanBnXkFtZTcwNDQ2MzQyMQ@@._V1_SX400_.jpg', 'After 300 years, three sister witches are resurrected in Salem Massachusetts on Halloween night, and it us up to two teenagers, a young girl, and an immortal cat to put an end to the witches reign of terror once and for all.', '1993-07-16 00:00:00'),
(84, 2013, 'The East', 'Zal Batmanglij', 'http://ia.media-imdb.com/images/M/MV5BMjEyNjQzMzg5Nl5BMl5BanBnXkFtZTcwMjExNzU1OQ@@._V1_SX400_.jpg', 'An operative for an elite private intelligence firm finds her priorities changing dramatically after she is tasked with infiltrating an anarchist group known for executing covert attacks upon major corporations.', '2013-01-20 00:00:00'),
(85, 2013, 'V/H/S/2', 'Simon Barrett', 'http://ia.media-imdb.com/images/M/MV5BODg4OTMxNDAxMV5BMl5BanBnXkFtZTcwMjM4ODQ0OQ@@._V1_SX400_.jpg', 'Searching for a missing student, two private investigators break into his house and find collection of VHS tapes. Viewing the horrific contents of each cassette, they realize there may be dark motives behind the student\'s disappearance.', '2013-01-19 00:00:00'),
(86, 2013, 'The Croods', 'Kirk De Micco', 'http://ia.media-imdb.com/images/M/MV5BMTcyOTc2OTA1Ml5BMl5BanBnXkFtZTcwOTI1MjkzOQ@@._V1_SX400_.jpg', 'After their cave is destroyed, a caveman family must trek through an unfamiliar fantastical world with the help of an inventive boy.', '2013-02-15 00:00:00'),
(87, 2013, 'Olympus Has Fallen', 'Antoine Fuqua', 'http://ia.media-imdb.com/images/M/MV5BMTkxNjIyNjE5OF5BMl5BanBnXkFtZTcwMTI3NzkxOQ@@._V1_SX400_.jpg', 'Disgraced former Presidential guard Mike Banning finds himself trapped inside the White House in the wake of a terrorist attack; using his inside knowledge, Banning works with national security to rescue the President from his kidnappers.', '2013-03-20 00:00:00'),
(88, 2013, 'Hummingbird', 'Steven Knight', 'http://ia.media-imdb.com/images/M/MV5BMjI0ODc3NjI4NV5BMl5BanBnXkFtZTcwOTc3MzI1OQ@@._V1_SX400_.jpg', 'Homeless and on the run from a military court martial, a damaged ex-special forces soldier navigating London\'s criminal underworld seizes an opportunity to assume another man\'s identity -- transforming into an avenging angel in the process.', '2013-05-09 00:00:00'),
(89, 2013, 'About Time', 'Richard Curtis', 'http://ia.media-imdb.com/images/M/MV5BMTA1ODUzMDA3NzFeQTJeQWpwZ15BbWU3MDgxMTYxNTk@._V1_SX400_.jpg', 'At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out not to be as easy as you might think.', '2013-06-27 00:00:00'),
(90, 2012, 'Mud', 'Jeff Nichols', 'http://ia.media-imdb.com/images/M/MV5BMTU2MzcyODgyNV5BMl5BanBnXkFtZTcwNTc4MDYwOQ@@._V1_SX400_.jpg', 'Two young boys encounter a fugitive and form a pact to help him evade the bounty hunters on his trail and to reunite him with his true love.', '2012-05-26 00:00:00'),
(91, 2012, 'Argo', 'Ben Affleck', 'http://ia.media-imdb.com/images/M/MV5BMTc3MjI0MjM0NF5BMl5BanBnXkFtZTcwMTYxMTQ1OA@@._V1_SX400_.jpg', 'Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980.', '2012-08-31 00:00:00'),
(92, 2012, 'Django Unchained', 'Quentin Tarantino', 'http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX400_.jpg', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', '2012-12-25 00:00:00'),
(93, 2013, 'Grown Ups 2', 'Dennis Dugan', 'http://ia.media-imdb.com/images/M/MV5BMTgwNTI2MDI0OF5BMl5BanBnXkFtZTcwMTk5MDg0OQ@@._V1_SX400_.jpg', 'After moving his family back to his hometown to be with his friends and their kids, Lenny finds out that between old bullies, new bullies, schizo bus drivers, drunk cops on skis, and 400 costumed party crashers sometimes crazy follows you.', '2013-07-11 00:00:00'),
(94, 2008, 'The Dark Knight', 'Christopher Nolan', 'http://ia.media-imdb.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX400_.jpg', 'When Batman, Gordon and Harvey Dent launch an assault on the mob, they let the clown out of the box, the Joker, bent on turning Gotham on itself and bringing any heroes down to his level.', '2008-07-14 00:00:00'),
(95, 2013, 'Planes', 'Klay Hall', 'http://ia.media-imdb.com/images/M/MV5BMjAwODc5NzYzOF5BMl5BanBnXkFtZTcwNTk4MjEzOQ@@._V1_SX400_.jpg', 'A cropdusting plane with a fear of heights lives his dream of competing in a famous around-the-world aerial race.', '2013-08-05 00:00:00'),
(96, 2013, 'Captain Phillips', 'Paul Greengrass', 'http://ia.media-imdb.com/images/M/MV5BMTQzNzExMDg3Ml5BMl5BanBnXkFtZTgwODU1NzEzMDE@._V1_SX400_.jpg', 'The true story of Captain Richard Phillips and the 2009 hijacking by Somali pirates of the US-flagged MV Maersk Alabama, the first American cargo ship to be hijacked in two hundred years.', '2013-09-27 00:00:00'),
(97, 2012, 'The Hobbit: An Unexpected Journey', 'Peter Jackson', 'http://ia.media-imdb.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_SX400_.jpg', 'A younger and more reluctant Hobbit, Bilbo Baggins, sets out on an \"unexpected journey\" to the Lonely Mountain with a spirited group of Dwarves to reclaim their stolen mountain home from a dragon named Smaug.', '2012-11-28 00:00:00'),
(98, 2014, 'Guardians of the Galaxy', 'James Gunn', 'http://ia.media-imdb.com/images/M/MV5BMTg3NDI5Mjg5MF5BMl5BanBnXkFtZTgwNzI2OTIzMDE@._V1_SX400_.jpg', 'A jet pilot gets stranded in space, and must unite a diverse team of aliens to form a squad capable of defeating cosmic threats.', '2014-07-31 00:00:00'),
(99, 2012, 'Les Miserables', 'Tom Hooper', 'http://ia.media-imdb.com/images/M/MV5BMTQ4NDI3NDg4M15BMl5BanBnXkFtZTcwMjY5OTI1OA@@._V1_SX400_.jpg', 'In 19th-century France, Jean Valjean, who for decades has been hunted by the ruthless policeman Javert after he breaks parole, agrees to care for factory worker Fantine\'s daughter, Cosette. The fateful decision changes their lives forever.', '2012-12-05 00:00:00'),
(100, 2013, 'The Kings of Summer', 'Jordan Vogt-Roberts', 'http://ia.media-imdb.com/images/M/MV5BMTc3ODA1NTI0MV5BMl5BanBnXkFtZTcwOTE4OTUzOQ@@._V1_SX400_.jpg', 'Three teenage friends, in the ultimate act of independence, decide to spend their summer building a house in the woods and living off the land.', '2013-01-19 00:00:00'),
(101, 2009, 'Mr. Nobody', 'Jaco Van Dormael', 'http://ia.media-imdb.com/images/M/MV5BMTg4ODkzMDQ3Nl5BMl5BanBnXkFtZTgwNTEwMTkxMDE@._V1_SX400_.jpg', 'A boy stands on a station platform as a train is about to leave. Should he go with his mother or stay with his father? An infinity of possibilities rise from this decision. As long as he doesn\'t choose, anything is possible.', '2009-09-12 00:00:00'),
(102, 2013, 'The Fifth Estate', 'Bill Condon', 'http://ia.media-imdb.com/images/M/MV5BMjY1MTY5NTg3M15BMl5BanBnXkFtZTgwMDQyMjgwMDE@._V1_SX400_.jpg', 'A dramatic thriller based on real events, THE FIFTH ESTATE reveals the quest to expose the deceptions and corruptions of power that turned an Internet upstart into the 21st century\'s most fiercely debated organization.', '2013-09-05 00:00:00'),
(103, 1997, 'Titanic', 'James Cameron', 'http://ia.media-imdb.com/images/M/MV5BMjExNzM0NDM0N15BMl5BanBnXkFtZTcwMzkxOTUwNw@@._V1_SX400_.jpg', 'A seventeen-year-old aristocrat, expecting to be married to a rich claimant by her mother, falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', '1997-11-01 00:00:00'),
(104, 2004, 'The Incredibles', 'Brad Bird', 'http://ia.media-imdb.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX400_.jpg', 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.', '2004-10-27 00:00:00'),
(105, 2014, 'Into the Woods', 'Rob Marshall', 'http://ia.media-imdb.com/images/M/MV5BMTY4OTE5NDYzOV5BMl5BanBnXkFtZTgwODcwMzMzMDE@._V1_SX400_.jpg', 'A witch conspires to teach important lessons to various characters of popular children\'s stories including Little Red Riding Hood, Cinderella, Jack and the Beanstalk and Rapunzel.', '2014-12-25 00:00:00'),
(106, 1994, 'Pulp Fiction', 'Quentin Tarantino', 'http://ia.media-imdb.com/images/M/MV5BMjE0ODk2NjczOV5BMl5BanBnXkFtZTYwNDQ0NDg4._V1_SX400_.jpg', 'The lives of two mob hit men, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', '1994-05-12 00:00:00'),
(107, 2013, 'The Call', 'Brad Anderson', 'http://ia.media-imdb.com/images/M/MV5BMjExNDkzNjAwOV5BMl5BanBnXkFtZTcwMDMzMzQwOQ@@._V1_SX400_.jpg', 'When a veteran 911 operator takes a life-altering call from a teenage girl who has just been abducted, she realizes that she must confront a killer from her past in order to save the girl\'s life.', '2013-03-14 00:00:00'),
(108, 2013, 'Side Effects', 'Steven Soderbergh', 'http://ia.media-imdb.com/images/M/MV5BMTc2MzY0NDAwOF5BMl5BanBnXkFtZTcwMTE1Mzc4OA@@._V1_SX400_.jpg', 'A young woman\'s world unravels when a drug prescribed by her psychiatrist has unexpected side effects.', '2013-02-08 00:00:00'),
(109, 2012, 'The Iceman', 'Ariel Vromen', 'http://ia.media-imdb.com/images/M/MV5BMTc3NjY3NzUyOF5BMl5BanBnXkFtZTcwMTA5NzAyOA@@._V1_SX400_.jpg', 'The true story of Richard Kuklinski, the notorious contract killer and family man. When finally arrested in 1986, neither his wife nor daughters have any clue about his real profession.', '2012-08-30 00:00:00'),
(110, 1939, 'The Wizard of Oz', 'Victor Fleming', 'http://ia.media-imdb.com/images/M/MV5BMTU0MTA2OTIwNF5BMl5BanBnXkFtZTcwMzA0Njk3OA@@._V1_SX400_.jpg', 'Dorothy Gale is swept away to a magical land in a tornado and embarks on a quest to see the Wizard who can help her return home.', '1939-08-12 00:00:00'),
(111, 2013, 'Big Sur', 'Michael Polish', 'http://ia.media-imdb.com/images/M/MV5BMjI3MDU0MDY2MF5BMl5BanBnXkFtZTgwNDY3NjUzMDE@._V1_SX400_.jpg', 'A recounting of Jack Kerouac\'s (here known by the name of his fictional alter-ego Jack Duluoz) three sojourns to the cabin in Big Sur, owned by poet Lawrence Ferlinghetti.', '2013-01-23 00:00:00'),
(112, 1985, 'The Breakfast Club', 'John Hughes', 'http://ia.media-imdb.com/images/M/MV5BMzYyNTQ1Nzk2M15BMl5BanBnXkFtZTcwODk0NTQyMQ@@._V1_SX400_.jpg', 'Five high school students, all different stereotypes, meet in detention, where they pour their hearts out to each other, and discover how they have a lot more in common than they thought.', '1985-02-07 00:00:00'),
(113, 2010, 'Inception', 'Christopher Nolan', 'http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX400_.jpg', 'A skilled extractor is offered a chance to regain his old life as payment for a task considered to be impossible.', '2010-07-08 00:00:00'),
(114, 2012, 'Hitchcock', 'Sacha Gervasi', 'http://ia.media-imdb.com/images/M/MV5BODAwNDI5NjIwN15BMl5BanBnXkFtZTcwNjc4ODc2OA@@._V1_SX400_.jpg', 'A love story between influential filmmaker Alfred Hitchcock and wife Alma Reville during the filming of [link=tt0054215] in 1959.', '2012-11-01 00:00:00'),
(115, 2014, 'The Expendables 3', 'Patrick Hughes', NULL, 'The third installment of the action-adventure franchise that follows the exploits of Barney Ross, Lee Christmas, and their associates.', '2014-08-13 00:00:00'),
(116, 2013, 'The Wolverine', 'James Mangold', 'http://ia.media-imdb.com/images/M/MV5BNzg1MDQxMTQ2OF5BMl5BanBnXkFtZTcwMTk3MjAzOQ@@._V1_SX400_.jpg', 'When Wolverine is summoned to Japan by an old acquaintance, he is embroiled in a conflict that forces him to confront his own demons.', '2013-07-16 00:00:00'),
(117, 2013, 'The Purge', 'James DeMonaco', 'http://ia.media-imdb.com/images/M/MV5BMTU0OTE1Nzk2NF5BMl5BanBnXkFtZTcwMjE5NDY0OQ@@._V1_SX400_.jpg', 'A family is held hostage for harboring the target of a murderous syndicate during the Purge, a 12-hour period in which any and all crime is legalized.', '2013-05-02 00:00:00'),
(118, 2013, 'Safe Haven', 'Lasse Hallstrom', 'http://ia.media-imdb.com/images/M/MV5BMTg4MzcxODA3OV5BMl5BanBnXkFtZTcwMTYzNDkwOQ@@._V1_SX400_.jpg', 'A young woman with a mysterious past lands in Southport, North Carolina where her bond with a widower forces her to confront the dark secret that haunts her.', '2013-02-13 00:00:00'),
(119, 2012, 'The Perks of Being a Wallflower', 'Stephen Chbosky', 'http://ia.media-imdb.com/images/M/MV5BMzIxOTQyODU1OV5BMl5BanBnXkFtZTcwMDQ4Mjg4Nw@@._V1_SX400_.jpg', 'An introvert freshman is taken under the wings of two seniors who welcome him to the real world.', '2012-09-08 00:00:00'),
(120, 2009, 'Star Trek', 'J.J. Abrams', 'http://ia.media-imdb.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX400_.jpg', 'The brash James T. Kirk tries to live up to his father\'s legacy with Mr. Spock keeping him in check as a vengeful, time-traveling Romulan creates black holes to destroy the Federation one planet at a time.', '2009-04-06 00:00:00'),
(121, 2013, 'One Direction: This Is Us', 'Morgan Spurlock', 'http://ia.media-imdb.com/images/M/MV5BMTk5NTIxNzg3Nl5BMl5BanBnXkFtZTcwMzc5MDE0OQ@@._V1_SX400_.jpg', 'A look at Niall, Zayn, Liam, Louis, and Harry\'s meteoric rise to fame, from their humble hometown beginnings and competing on the X-Factor, to conquering the world and performing at London\'s famed O2 Arena.', '2013-08-20 00:00:00'),
(122, 2012, 'Cloud Atlas', 'Tom Tykwer', 'http://ia.media-imdb.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_SX400_.jpg', 'An exploration of how the actions of individual lives impact one another in the past, present and future, as one soul is shaped from a killer into a hero, and an act of kindness ripples across centuries to inspire a revolution.', '2012-09-08 00:00:00'),
(123, 2011, 'Harry Potter and the Deathly Hallows: Part 2', 'David Yates', 'http://ia.media-imdb.com/images/M/MV5BMTY2MTk3MDQ1N15BMl5BanBnXkFtZTcwMzI4NzA2NQ@@._V1_SX400_.jpg', 'Harry, Ron and Hermione search for Voldemort\'s remaining Horcruxes in their effort to destroy the Dark Lord.', '2011-07-07 00:00:00'),
(124, 2013, 'Empire State', 'Dito Montiel', 'http://ia.media-imdb.com/images/M/MV5BMjExOTY4MDEzNF5BMl5BanBnXkFtZTcwNzIyMTY3OQ@@._V1_SX400_.jpg', 'A drama centered on two childhood friends who plan to rob an armored car depository, and the NYPD officer who stands in their way.', '2013-03-19 00:00:00'),
(125, 2013, 'The Frozen Ground', 'Scott Walker', 'http://ia.media-imdb.com/images/M/MV5BMjA0MjAyMjIxMl5BMl5BanBnXkFtZTcwNTQ1NDc2OQ@@._V1_SX400_.jpg', 'An Alaska State Trooper partners with a young woman who escaped the clutches of serial killer Robert Hansen to bring the murderer to justice. Based on actual events.', '2013-07-11 00:00:00'),
(126, 2013, 'The Wolf of Wall Street', 'Martin Scorsese', 'http://ia.media-imdb.com/images/M/MV5BMTQ5OTI2MTQ1MV5BMl5BanBnXkFtZTcwMjY0Njk2OQ@@._V1_SX400_.jpg', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker living the high life to his fall involving crime, corruption and the federal government.', '2013-11-14 00:00:00'),
(127, 2011, 'Thor', 'Kenneth Branagh', 'http://ia.media-imdb.com/images/M/MV5BMTYxMjA5NDMzNV5BMl5BanBnXkFtZTcwOTk2Mjk3NA@@._V1_SX400_.jpg', 'The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.', '2011-04-21 00:00:00'),
(128, 2010, 'I Spit on Your Grave', 'Steven R. Monroe', 'http://ia.media-imdb.com/images/M/MV5BMTkxMTE3NzEzMl5BMl5BanBnXkFtZTcwMzc4MTU2Mw@@._V1_SX400_.jpg', 'A writer who is brutalized during her cabin retreat seeks revenge on her attackers, who left her for dead.', '2010-05-01 00:00:00'),
(129, 2004, 'The Notebook', 'Nick Cassavetes', 'http://ia.media-imdb.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_SX400_.jpg', 'A poor and passionate young man falls in love with a rich young woman and gives her a sense of freedom. They soon are separated by their social differences.', '2004-05-20 00:00:00'),
(130, 2012, 'Looper', 'Rian Johnson', 'http://ia.media-imdb.com/images/M/MV5BMTY3NTY0MjEwNV5BMl5BanBnXkFtZTcwNTE3NDA1OA@@._V1_SX400_.jpg', 'In 2074, when the mob wants to get rid of someone, the target is sent 30 years into the past, where a hired gun awaits. Someone like Joe, who one day learns the mob wants to \'close the loop\' by transporting back Joe\'s future self.', '2012-09-06 00:00:00'),
(131, 2013, 'The Spectacular Now', 'James Ponsoldt', 'http://ia.media-imdb.com/images/M/MV5BMjA5MTc0NTkzM15BMl5BanBnXkFtZTcwODEwNjE3OQ@@._V1_SX400_.jpg', 'A hard-partying high school senior\'s philosophy on life changes when he meets the not-so-typical \"nice girl.\"', '2013-01-18 00:00:00'),
(132, 2013, 'The Heat', 'Paul Feig', 'http://ia.media-imdb.com/images/M/MV5BNDEwMTg2OTI5MF5BMl5BanBnXkFtZTcwNjgyNjkzOQ@@._V1_SX400_.jpg', 'An uptight FBI Special Agent is paired with a foul-mouthed Boston cop to take down a ruthless drug lord.', '2013-06-27 00:00:00'),
(133, 2009, 'Inglourious Basterds', 'Quentin Tarantino', 'http://ia.media-imdb.com/images/M/MV5BMjIzMDI4MTUzOV5BMl5BanBnXkFtZTcwNDY3NjA3Mg@@._V1_SX400_.jpg', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.', '2009-05-20 00:00:00'),
(134, 1972, 'The Godfather', 'Francis Ford Coppola', 'http://ia.media-imdb.com/images/M/MV5BMjEyMjcyNDI4MF5BMl5BanBnXkFtZTcwMDA5Mzg3OA@@._V1_SX400_.jpg', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', '1972-03-15 00:00:00'),
(135, 2013, 'Filth', 'Jon S. Baird', 'http://ia.media-imdb.com/images/M/MV5BODc3MjY5NTQxNl5BMl5BanBnXkFtZTcwNTQxMzczOQ@@._V1_SX400_.jpg', 'A bipolar, bigoted junkie cop manipulates and hallucinates his way through the festive season in a bid to secure promotion and win back his wife and daughter.', '2013-09-16 00:00:00'),
(136, 1999, 'Fight Club', 'David Fincher', 'http://ia.media-imdb.com/images/M/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX400_.jpg', 'An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...', '1999-09-10 00:00:00'),
(137, 2013, 'Escape from Tomorrow', 'Randy Moore', 'http://ia.media-imdb.com/images/M/MV5BNTIxNjcxOTgxM15BMl5BanBnXkFtZTgwMjYzODEzMDE@._V1_SX400_.jpg', 'In a world of fake castles and anthropomorphic rodents, an epic battle begins when an unemployed father\'s sanity is challenged by a chance encounter with two underage girls on holiday.', '2013-01-18 00:00:00'),
(138, 1976, 'Carrie', 'Brian De Palma', 'http://ia.media-imdb.com/images/M/MV5BMTg1NjEwOTUxN15BMl5BanBnXkFtZTcwOTI0MTU0NA@@._V1_SX400_.jpg', 'A young, abused and timid 17-year-old girl discovers she has telekinesis, and gets pushed to the limit on the night of her school\'s prom by a humiliating prank.', '1976-11-03 00:00:00'),
(139, 2013, 'Enough Said', 'Nicole Holofcener', 'http://ia.media-imdb.com/images/M/MV5BMjI2MjIwMDk2Ml5BMl5BanBnXkFtZTcwNTQ1MzQ5OQ@@._V1_SX400_.jpg', 'A divorced woman who decides to pursue the man she\'s interested in learns he\'s her new friend\'s ex-husband.', '2013-09-07 00:00:00'),
(140, 2012, 'Prometheus', 'Ridley Scott', 'http://ia.media-imdb.com/images/M/MV5BMTY3NzIyNTA2NV5BMl5BanBnXkFtZTcwNzE2NjI4Nw@@._V1_SX400_.jpg', 'A team of explorers discover a clue to the origins of mankind on Earth, leading them on a journey to the darkest corners of the universe. There, they must fight a terrifying battle to save the future of the human race.', '2012-05-30 00:00:00'),
(141, 2006, 'The Departed', 'Martin Scorsese', 'http://ia.media-imdb.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX400_.jpg', 'An undercover state cop who has infiltrated an Irish gang and a mole in the police force working for the same mob race to track down and identify each other before being exposed to the enemy, after both sides realize their outfit has a rat.', '2006-09-26 00:00:00'),
(142, 1994, 'Dumb & Dumber', 'Peter Farrelly', 'http://ia.media-imdb.com/images/M/MV5BMTIzNDI5MTc0M15BMl5BanBnXkFtZTYwMjM5NDU5._V1_SX400_.jpg', 'The cross-country adventures of two good-hearted but incredibly stupid friends.', '1994-12-06 00:00:00'),
(143, 2013, 'Romeo and Juliet', 'Carlo Carlei', 'http://ia.media-imdb.com/images/M/MV5BMTA3MjQwOTg4MTheQTJeQWpwZ15BbWU3MDM3NDE0OTk@._V1_SX400_.jpg', 'When the star-crossed lovers of two enemy families meet, forbidden love ensues.', '2013-09-24 00:00:00'),
(144, 2009, 'Cloudy with a Chance of Meatballs', 'Phil Lord', 'http://ia.media-imdb.com/images/M/MV5BMTg0MjAwNDI5MV5BMl5BanBnXkFtZTcwODkyMzg2Mg@@._V1_SX400_.jpg', 'The most delicious event since macaroni met cheese. Inspired by the beloved children\'s book, the film focuses on a town where food falls from the sky like rain.', '2009-09-16 00:00:00'),
(145, 2013, 'CBGB', 'Randall Miller', 'http://ia.media-imdb.com/images/M/MV5BMTg1NDcxODY0OV5BMl5BanBnXkFtZTgwOTgwMzQxMDE@._V1_SX400_.jpg', 'A look at the New York City punk-rock scene and the venerable nightclub, CBGB.', '2013-09-05 00:00:00'),
(146, 2013, 'The Counselor', 'Ridley Scott', 'http://ia.media-imdb.com/images/M/MV5BMTc3ODk0MTY0N15BMl5BanBnXkFtZTgwOTU2MTEzMDE@._V1_SX400_.jpg', 'A lawyer finds himself in over his head when he gets involved in drug trafficking.', '2013-10-25 00:00:00'),
(147, 2013, 'Kill Your Darlings', 'John Krokidas', 'http://ia.media-imdb.com/images/M/MV5BMjA4MzAxMTE1N15BMl5BanBnXkFtZTgwMDY2OTIxMDE@._V1_SX400_.jpg', 'A murder in 1944 draws together the great poets of the beat generation: Allen Ginsberg, Jack Kerouac and William Burroughs.', '2013-01-18 00:00:00'),
(148, 2013, 'Only God Forgives', 'Nicolas Winding Refn', 'http://ia.media-imdb.com/images/M/MV5BMzE5NzcxMTk5NF5BMl5BanBnXkFtZTcwNjE2MDg2OQ@@._V1_SX400_.jpg', 'Julian, a drug-smuggler thriving in Bangkok\'s criminal underworld, sees his life get even more complicated when his mother compels him to find and kill whoever is responsible for his brother\'s recent death.', '2013-05-22 00:00:00');
INSERT INTO `movies` (`id`, `year`, `title`, `directors`, `image_url`, `plot`, `release_date`) VALUES
(149, 2013, 'Evil Dead', 'Fede Alvarez', 'http://ia.media-imdb.com/images/M/MV5BNTQ3OTkwNTgyN15BMl5BanBnXkFtZTcwNTAzOTAzOQ@@._V1_SX400_.jpg', 'Five friends head to a remote cabin, where the discovery of a Book of the Dead leads them to unwittingly summon up demons living in the nearby woods. The evil presence possesses them until only one is left to fight for survival.', '2013-03-08 00:00:00'),
(150, 2012, 'Stuck in Love', 'Josh Boone', 'http://ia.media-imdb.com/images/M/MV5BMTU1NzI5MDU3OV5BMl5BanBnXkFtZTcwNTE0NDMzOQ@@._V1_SX400_.jpg', 'An acclaimed writer, his ex-wife, and their teenaged children come to terms with the complexities of love in all its forms over the course of one tumultuous year.', '2012-09-09 00:00:00'),
(151, 2013, 'Bad Grandpa', 'Jeff Tremaine', 'http://ia.media-imdb.com/images/M/MV5BMTg4NjIwMTI5OV5BMl5BanBnXkFtZTgwNjU1MTMyMDE@._V1_SX400_.jpg', '86-year-old Irving Zisman is on a journey across America with the most unlikely companion: his 8 year-old grandson, Billy.', '2013-10-23 00:00:00'),
(152, 2011, 'You\'re Next', 'Adam Wingard', 'http://ia.media-imdb.com/images/M/MV5BMTQwODAxMTE1NF5BMl5BanBnXkFtZTcwNTQ0MjY3OQ@@._V1_SX400_.jpg', 'When the Davison family comes under attack during their wedding anniversary getaway, the gang of mysterious killers soon learns that one of victims harbors a secret talent for fighting back.', '2011-09-10 00:00:00'),
(153, 2011, 'Crazy, Stupid, Love.', 'Glenn Ficarra', 'http://ia.media-imdb.com/images/M/MV5BMTg2MjkwMTM0NF5BMl5BanBnXkFtZTcwMzc4NDg2NQ@@._V1_SX400_.jpg', 'A middle-aged husband\'s life changes dramatically when his wife asks him for a divorce. He seeks to rediscover his manhood with the help of a newfound friend, Jacob, learning to pick up girls at bars.', '2011-07-28 00:00:00'),
(154, 2013, 'Scenic Route', 'Kevin Goetz', 'http://ia.media-imdb.com/images/M/MV5BMjAyNjIyOTU0M15BMl5BanBnXkFtZTcwNTUwOTI2OQ@@._V1_SX400_.jpg', 'Tensions rise between lifelong friends Mitchell and Carter after their truck breaks down on an isolated desert road as they start to attack each other\'s life decisions with unwavering brutality.', '2013-03-09 00:00:00'),
(155, 2011, 'The Awakening', 'Nick Murphy', 'http://ia.media-imdb.com/images/M/MV5BMzk0ODc1NDMxOV5BMl5BanBnXkFtZTcwNTAzMzgwOA@@._V1_SX400_.jpg', 'In 1921, England is overwhelmed by the loss and grief of World War I. Hoax exposer Florence Cathcart visits a boarding school to explain sightings of a child ghost. Everything she believes unravels as the \'missing\' begin to show themselves.', '2011-09-16 00:00:00'),
(156, 2012, 'Zero Dark Thirty', 'Kathryn Bigelow', 'http://ia.media-imdb.com/images/M/MV5BMTQ4OTUyNzcwN15BMl5BanBnXkFtZTcwMTQ1NDE3OA@@._V1_SX400_.jpg', 'A chronicle of the decade-long hunt for al-Qaeda terrorist leader [link=nm1136915] after the September 2001 attacks, and his death at the hands of the Navy S.E.A.L. Team 6 in May 2011.', '2012-12-19 00:00:00'),
(157, 2006, '300', 'Zack Snyder', 'http://ia.media-imdb.com/images/M/MV5BMjAzNTkzNjcxNl5BMl5BanBnXkFtZTYwNDA4NjE3._V1_SX400_.jpg', 'King Leonidas and a force of 300 men fight the Persians at Thermopylae in 480 B.C.', '2006-12-09 00:00:00'),
(158, 2011, 'Conan the Barbarian', 'Marcus Nispel', 'http://ia.media-imdb.com/images/M/MV5BMTQ1NDUyODk5NF5BMl5BanBnXkFtZTcwODk0MjIwNg@@._V1_SX400_.jpg', 'An vengeful barbarian warrior sets off to get his revenge on the evil warlord who attacked his village and murdered his father when he was a boy.', '2011-08-11 00:00:00'),
(159, 2012, 'The Twilight Saga: Breaking Dawn - Part 2', 'Bill Condon', 'http://ia.media-imdb.com/images/M/MV5BMTcyMzUyMzY1OF5BMl5BanBnXkFtZTcwNDQ4ODk1OA@@._V1_SX400_.jpg', 'After the birth of Renesmee, the Cullens gather other vampire clans in order to protect the child from a false allegation that puts the family in front of the Volturi.', '2012-11-14 00:00:00'),
(160, 2008, 'Iron Man', 'Jon Favreau', 'http://ia.media-imdb.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX400_.jpg', 'When wealthy industrialist Tony Stark is forced to build an armored suit after a life-threatening incident, he ultimately decides to use its technology to fight against evil.', '2008-04-14 00:00:00'),
(161, 2013, 'Oz the Great and Powerful', 'Sam Raimi', 'http://ia.media-imdb.com/images/M/MV5BMjMyMzQ1ODM1MF5BMl5BanBnXkFtZTcwMjE2MTQxOQ@@._V1_SX400_.jpg', 'A small-time magician is swept away to an enchanted land and is forced into a power struggle between three witches.', '2013-02-14 00:00:00'),
(162, 2010, 'Despicable Me', 'Pierre Coffin', 'http://ia.media-imdb.com/images/M/MV5BMTY3NjY0MTQ0Nl5BMl5BanBnXkFtZTcwMzQ2MTc0Mw@@._V1_SX400_.jpg', 'When a criminal mastermind uses a trio of orphan girls as pawns for a grand scheme, he finds their love is profoundly changing him for the better.', '2010-06-20 00:00:00'),
(163, 2013, 'Movie 43', 'Elizabeth Banks', 'http://ia.media-imdb.com/images/M/MV5BMTg4NzQ3NDM1Nl5BMl5BanBnXkFtZTcwNjEzMjM3OA@@._V1_SX400_.jpg', 'A series of interconnected short films follows a washed-up producer as he pitches insane story lines featuring some of the biggest stars in Hollywood.', '2013-01-01 00:00:00'),
(164, 2013, 'Warm Bodies', 'Jonathan Levine', 'http://ia.media-imdb.com/images/M/MV5BMTQ4MjY2MjMzOV5BMl5BanBnXkFtZTcwMDUxNzIwOQ@@._V1_SX400_.jpg', 'After a highly unusual zombie saves a still-living girl from an attack, the two form a relationship that sets in motion events that might transform the entire lifeless world.', '2013-01-16 00:00:00'),
(165, 2012, 'Flight', 'Robert Zemeckis', 'http://ia.media-imdb.com/images/M/MV5BMTUxMjI1OTMxNl5BMl5BanBnXkFtZTcwNjc3NTY1OA@@._V1_SX400_.jpg', 'An airline pilot saves almost all his passengers on his malfunctioning airliner which eventually crashed, but an investigation into the accident reveals something troubling.', '2012-10-14 00:00:00'),
(166, 2014, 'I, Frankenstein', 'Stuart Beattie', 'http://ia.media-imdb.com/images/M/MV5BMTQzNDA3MjQwMl5BMl5BanBnXkFtZTcwNTgyNTc4OQ@@._V1_SX400_.jpg', 'Frankenstein\'s creature finds himself caught in an all-out, centuries old war between two immortal clans.', '2014-01-22 00:00:00'),
(167, 2013, 'G.I. Joe: Retaliation', 'Jon M. Chu', 'http://ia.media-imdb.com/images/M/MV5BNzk5ODM0OTQ0N15BMl5BanBnXkFtZTcwODg2ODE4OA@@._V1_SX400_.jpg', 'The G.I. Joes are not only fighting their mortal enemy Cobra; they are forced to contend with threats from within the government that jeopardize their very existence.', '2013-03-11 00:00:00'),
(168, 2014, '300: Rise of an Empire', 'Noam Murro', 'http://ia.media-imdb.com/images/M/MV5BMTEwNTU2MjAwMDdeQTJeQWpwZ15BbWU3MDk2Njc2Njk@._V1_SX400_.jpg', 'The Greek general Themistocles battles an invading army of Persians under the mortal-turned-god, Xerxes.', '2014-03-05 00:00:00'),
(169, 2001, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'http://ia.media-imdb.com/images/M/MV5BNTEyMjAwMDU1OV5BMl5BanBnXkFtZTcwNDQyNTkxMw@@._V1_SX400_.jpg', 'A meek hobbit of The Shire and eight companions set out on a journey to Mount Doom to destroy the One Ring and the dark lord Sauron.', '2001-12-10 00:00:00'),
(170, 2013, 'Red 2', 'Dean Parisot', 'http://ia.media-imdb.com/images/M/MV5BMjI2ODQ4ODY3Nl5BMl5BanBnXkFtZTcwNTc2NzE1OQ@@._V1_SX400_.jpg', 'Retired C.I.A. agent Frank Moses reunites his unlikely team of elite operatives for a global quest to track down a missing portable nuclear device.', '2013-07-18 00:00:00'),
(171, 2013, 'Anchorman 2: The Legend Continues', 'Adam McKay', 'http://ia.media-imdb.com/images/M/MV5BMTM5NTY0NTUzOV5BMl5BanBnXkFtZTcwMDY2MzA3OQ@@._V1_SX400_.jpg', 'With the 70s behind him, San Diego\'s top rated newsman, Ron Burgundy, returns to take New York\'s first 24-hour news channel by storm.', '2013-12-19 00:00:00'),
(172, 2012, 'Dredd', 'Pete Travis', 'http://ia.media-imdb.com/images/M/MV5BODkyNDQzMzUzOF5BMl5BanBnXkFtZTcwODYyMDEyOA@@._V1_SX400_.jpg', 'In a violent, futuristic city where the police have the authority to act as judge, jury and executioner, a cop teams with a trainee to take down a gang that deals the reality-altering drug, SLO-MO.', '2012-07-11 00:00:00'),
(173, 2013, 'The Smurfs 2', 'Raja Gosnell', 'http://ia.media-imdb.com/images/M/MV5BMTkyNDUxODg3MV5BMl5BanBnXkFtZTcwNjE5OTY2OQ@@._V1_SX400_.jpg', 'The Smurfs team up with their human friends to rescue Smurfette, who has been kidnapped by Gargamel since she knows a secret spell that can turn the evil sorcerer\'s newest creation - creatures called the Naughties - into real Smurfs.', '2013-07-28 00:00:00'),
(174, 2001, 'Harry Potter and the Sorcerer\'s Stone', 'Chris Columbus', 'http://ia.media-imdb.com/images/M/MV5BMTYwNTM5NDkzNV5BMl5BanBnXkFtZTYwODQ4MzY5._V1_SX400_.jpg', 'Rescued from the outrageous neglect of his aunt and uncle, a young boy with a great destiny proves his worth while attending Hogwarts School of Witchcraft and Wizardry.', '2001-11-04 00:00:00'),
(175, 2012, '21 Jump Street', 'Phil Lord', 'http://ia.media-imdb.com/images/M/MV5BMTc3NzQ3OTg3NF5BMl5BanBnXkFtZTcwMjk5OTcxNw@@._V1_SX400_.jpg', 'A pair of underachieving cops are sent back to a local high school to blend in and bring down a synthetic drug ring.', '2012-03-12 00:00:00'),
(176, 1980, 'The Shining', 'Stanley Kubrick', 'http://ia.media-imdb.com/images/M/MV5BODMxMjE3NTA4Ml5BMl5BanBnXkFtZTgwNDc0NTIxMDE@._V1_SX400_.jpg', 'A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.', '1980-05-23 00:00:00'),
(177, 2012, 'The Cabin in the Woods', 'Drew Goddard', 'http://ia.media-imdb.com/images/M/MV5BNTUxNzYyMjg2N15BMl5BanBnXkFtZTcwMTExNzExNw@@._V1_SX400_.jpg', 'Five friends go for a break at a remote cabin in the woods, where they get more than they bargained for. Together, they must discover the truth behind the cabin in the woods.', '2012-03-09 00:00:00'),
(178, 2013, 'Turbo', 'David Soren', 'http://ia.media-imdb.com/images/M/MV5BMTA4NTgwMjM5MzheQTJeQWpwZ15BbWU3MDg2ODA1ODk@._V1_SX400_.jpg', 'A freak accident might just help an everyday garden snail achieve his biggest dream: winning the Indy 500.', '2013-07-17 00:00:00'),
(179, 2013, 'The Lone Ranger', 'Gore Verbinski', 'http://ia.media-imdb.com/images/M/MV5BMjI3Mjk5MTUxOV5BMl5BanBnXkFtZTcwNTMyNzY3OQ@@._V1_SX400_.jpg', 'Native American warrior Tonto recounts the untold tales that transformed John Reid, a man of the law, into a legend of justice.', '2013-06-22 00:00:00'),
(180, 2011, 'Moneyball', 'Bennett Miller', 'http://ia.media-imdb.com/images/M/MV5BMjAxOTU3Mzc1M15BMl5BanBnXkFtZTcwMzk1ODUzNg@@._V1_SX400_.jpg', 'Oakland A\'s general manager Billy Beane\'s successful attempt to assemble a baseball team on a lean budget by employing computer-generated analysis to acquire new players.', '2011-09-09 00:00:00'),
(181, 2001, 'Donnie Darko', 'Richard Kelly', 'http://ia.media-imdb.com/images/M/MV5BMTczMzE4Nzk3N15BMl5BanBnXkFtZTcwNDg5Mjc4NA@@._V1_SX400_.jpg', 'A troubled teenager is plagued by visions of a large bunny rabbit that manipulates him to commit a series of crimes, after narrowly escaping a bizarre accident.', '2001-01-19 00:00:00'),
(182, 2011, 'Drive', 'Nicolas Winding Refn', 'http://ia.media-imdb.com/images/M/MV5BOTM1ODQ0Nzc4NF5BMl5BanBnXkFtZTcwMTM0MjQyNg@@._V1_SX400_.jpg', 'A mysterious Hollywood stuntman, mechanic and getaway driver lands himself in trouble when he helps out his neighbor.', '2011-05-20 00:00:00'),
(183, 2013, 'The Internship', 'Shawn Levy', 'http://ia.media-imdb.com/images/M/MV5BMjM1MzczMDgwOV5BMl5BanBnXkFtZTcwMDM4NjM2OQ@@._V1_SX400_.jpg', 'Two salesmen whose careers have been torpedoed by the digital age find their way into a coveted internship at Google, where they must compete with a group of young, tech-savvy geniuses for a shot at employment.', '2013-06-05 00:00:00'),
(184, 2012, 'Skyfall', 'Sam Mendes', 'http://ia.media-imdb.com/images/M/MV5BMjM1MzMzOTA3MV5BMl5BanBnXkFtZTcwOTE3NzA1OA@@._V1_SX400_.jpg', 'Bond\'s loyalty to M is tested when her past comes back to haunt her. Whilst MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.', '2012-10-23 00:00:00'),
(185, 2004, 'Mean Girls', 'Mark Waters', 'http://ia.media-imdb.com/images/M/MV5BMjE1MDQ4MjI1OV5BMl5BanBnXkFtZTcwNzcwODAzMw@@._V1_SX400_.jpg', 'Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.', '2004-04-19 00:00:00'),
(186, 2006, 'The Prestige', 'Christopher Nolan', 'http://ia.media-imdb.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX400_.jpg', 'The rivalry between two magicians becomes more exacerbated by their attempt to perform the ultimate illusion.', '2006-10-17 00:00:00'),
(187, 2011, 'Intouchables', 'Olivier Nakache', 'http://ia.media-imdb.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX400_.jpg', 'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caretaker.', '2011-09-23 00:00:00'),
(188, 2013, 'Nebraska', 'Alexander Payne', 'http://ia.media-imdb.com/images/M/MV5BMTU2Mjk2NDkyMl5BMl5BanBnXkFtZTgwNTk0NzcyMDE@._V1_SX400_.jpg', 'An aging, booze-addled father makes the trip from Montana to Nebraska with his estranged son in order to claim a million dollar Mega Sweepstakes Marketing prize.', '2013-05-23 00:00:00'),
(189, 2013, 'Zero Charisma', 'Katie Graham', 'http://ia.media-imdb.com/images/M/MV5BMTQ3MDU4MTI3NV5BMl5BanBnXkFtZTgwMzg5NDYyMDE@._V1_SX400_.jpg', 'An overgrown nerd who serves as Grand Master of a fantasy board game finds his role as leader of the misfits put into jeopardy when a new initiate enters the group.', '2013-04-25 00:00:00'),
(190, 2013, 'American Hustle', 'David O. Russell', 'http://ia.media-imdb.com/images/M/MV5BMjkyNDY3Mzg2Ml5BMl5BanBnXkFtZTgwMzU0OTYzMDE@._V1_SX400_.jpg', 'The story of a con artist and his partner in crime, who were forced to work with a federal agent to turn the tables on other cons, mobsters, and politicians - namely, the volatile mayor of impoverished Camden, New Jersey.', '2013-12-13 00:00:00'),
(191, 1985, 'Back to the Future', 'Robert Zemeckis', 'http://ia.media-imdb.com/images/M/MV5BMTk4OTQ1OTMwN15BMl5BanBnXkFtZTcwOTIwMzM3MQ@@._V1_SX400_.jpg', 'A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown, and must make sure his high-school-age parents unite in order to save his own existence.', '1985-07-03 00:00:00'),
(192, 2013, 'Adore', 'Anne Fontaine', 'http://ia.media-imdb.com/images/M/MV5BMjg5ODY2MzcwMF5BMl5BanBnXkFtZTcwODEwNjQ3OQ@@._V1_SX400_.jpg', 'A pair of childhood friends and neighbors fall for each other\'s sons.', '2013-01-18 00:00:00'),
(193, 2000, 'Requiem for a Dream', 'Darren Aronofsky', 'http://ia.media-imdb.com/images/M/MV5BMzM2OTYwMTY4Nl5BMl5BanBnXkFtZTcwMjU1Njg3OA@@._V1_SX400_.jpg', 'The drug-induced utopias of four Coney Island individuals are shattered when their addictions become stronger.', '2000-05-14 00:00:00'),
(194, 2013, 'Monsters University', 'Dan Scanlon', 'http://ia.media-imdb.com/images/M/MV5BMTUyODgwMDU3M15BMl5BanBnXkFtZTcwOTM4MjcxOQ@@._V1_SX400_.jpg', 'A look at the relationship between Mike and Sulley during their days at Monsters University -- when they weren\'t necessarily the best of friends.', '2013-06-08 00:00:00'),
(195, 2013, 'Parkland', 'Peter Landesman', 'http://ia.media-imdb.com/images/M/MV5BMjE2NjkwNDE2MF5BMl5BanBnXkFtZTgwNDY5ODIxMDE@._V1_SX400_.jpg', 'A recounting of the chaotic events that occurred at Dallas\' Parkland Hospital on the day U.S. President John F. Kennedy was assassinated.', '2013-09-01 00:00:00'),
(196, 2010, 'She\'s Out of My League', 'Jim Field Smith', 'http://ia.media-imdb.com/images/M/MV5BMTkwMTY5ODA1MF5BMl5BanBnXkFtZTcwODYyNzAxMw@@._V1_SX400_.jpg', 'An average Joe meets the perfect woman, but his lack of confidence and the influence of his friends and family begin to pick away at the relationship.', '2010-03-11 00:00:00'),
(197, 1999, 'American Beauty', 'Sam Mendes', 'http://ia.media-imdb.com/images/M/MV5BOTU1MzExMDg3N15BMl5BanBnXkFtZTcwODExNDg3OA@@._V1_SX400_.jpg', 'Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation for his daughter\'s attractive friend.', '1999-09-08 00:00:00'),
(198, 2013, 'Homefront', 'Gary Fleder', 'http://ia.media-imdb.com/images/M/MV5BMTUwOTAzNzAwMl5BMl5BanBnXkFtZTgwOTc1NDIyMDE@._V1_SX400_.jpg', 'A former DEA agent moves his family to a quiet town, where he soon tangles with a local meth druglord.', '2013-11-27 00:00:00'),
(199, 2012, 'Magic Mike', 'Steven Soderbergh', 'http://ia.media-imdb.com/images/M/MV5BMTQzMDMzOTA5M15BMl5BanBnXkFtZTcwMjc4MTg4Nw@@._V1_SX400_.jpg', 'A male stripper teaches a younger performer how to party, pick up women, and make easy money.', '2012-06-24 00:00:00'),
(200, 2009, 'The Hangover', 'Todd Phillips', 'http://ia.media-imdb.com/images/M/MV5BMTU1MDA1MTYwMF5BMl5BanBnXkFtZTcwMDcxMzA1Mg@@._V1_SX400_.jpg', 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.', '2009-05-30 00:00:00'),
(201, 2012, 'Lawless', 'John Hillcoat', 'http://ia.media-imdb.com/images/M/MV5BMjAxNjUyNjUwN15BMl5BanBnXkFtZTcwMDgwOTIyOA@@._V1_SX400_.jpg', 'Set in Depression-era Franklin County, Virginia, a bootlegging gang is threatened by a new deputy and other authorities who want a cut of their profits.', '2012-05-19 00:00:00'),
(202, 2014, 'Teenage Mutant Ninja Turtles', 'Jonathan Liebesman', NULL, 'Aliens invade Earth and inadvertently spawn a quartet of mutated reptilian warriors, the Ninja Turtles, who rise up against them to defend the world.', '2014-05-15 00:00:00'),
(203, 2011, 'Pirates of the Caribbean: On Stranger Tides', 'Rob Marshall', 'http://ia.media-imdb.com/images/M/MV5BMjE5MjkwODI3Nl5BMl5BanBnXkFtZTcwNjcwMDk4NA@@._V1_SX400_.jpg', 'Jack Sparrow and Barbossa embark on a quest to find the elusive fountain of youth, only to discover that Blackbeard and his daughter are after it too.', '2011-05-07 00:00:00'),
(204, 2013, 'Trance', 'Danny Boyle', 'http://ia.media-imdb.com/images/M/MV5BMjMzNjU1MTg5NF5BMl5BanBnXkFtZTcwMTExMTcwOQ@@._V1_SX400_.jpg', 'An art auctioneer who has become mixed up with a group of criminals partners with a hypnotherapist in order to recover a lost painting.', '2013-03-27 00:00:00'),
(205, 2013, 'One Chance', 'David Frankel', 'http://ia.media-imdb.com/images/M/MV5BMTU4NzkxMzY2Nl5BMl5BanBnXkFtZTgwMjM5NDYxMDE@._V1_SX400_.jpg', 'The true story of Paul Potts, a shy, bullied shop assistant by day and an amateur opera singer by night who became a phenomenon after being chosen for -- and ultimately winning -- \"Britain\'s Got Talent\".', '2013-09-09 00:00:00'),
(206, 2013, 'The Colony', 'Jeff Renfroe', 'http://ia.media-imdb.com/images/M/MV5BNzAzNzEzNDA4OF5BMl5BanBnXkFtZTcwOTUwODA3OQ@@._V1_SX400_.jpg', 'Forced underground by the next ice age, a struggling outpost of survivors must fight to preserve humanity against a threat even more savage than nature.', '2013-04-26 00:00:00'),
(207, 2003, 'Love Actually', 'Richard Curtis', 'http://ia.media-imdb.com/images/M/MV5BMTY4NjQ5NDc0Nl5BMl5BanBnXkFtZTYwNjk5NDM3._V1_SX400_.jpg', 'Follows the lives of eight very different couples in dealing with their love lives in various loosely and interrelated tales all set during a frantic month before Christmas in London, England.', '2003-09-07 00:00:00'),
(208, 2012, 'Ted', 'Seth MacFarlane', 'http://ia.media-imdb.com/images/M/MV5BMTQ1OTU0ODcxMV5BMl5BanBnXkFtZTcwOTMxNTUwOA@@._V1_SX400_.jpg', 'As the result of a childhood wish, John Bennett\'s teddy bear, Ted, came to life and has been by John\'s side ever since - a friendship that\'s tested when Lori, John\'s girlfriend of four years, wants more from their relationship.', '2012-06-29 00:00:00'),
(209, 2014, 'Maleficent', 'Robert Stromberg', 'http://ia.media-imdb.com/images/M/MV5BMTk1OTk1MDMxNV5BMl5BanBnXkFtZTgwODMwMzQwMDE@._V1_SX400_.jpg', 'The \"Sleeping Beauty\" tale is told from the perspective of the villainous Maleficent and looks at the events that hardened her heart and drove her to curse young Princess Aurora.', '2014-05-30 00:00:00'),
(210, 2008, 'Twilight', 'Catherine Hardwicke', 'http://ia.media-imdb.com/images/M/MV5BMTQ2NzUxMTAxN15BMl5BanBnXkFtZTcwMzEyMTIwMg@@._V1_SX400_.jpg', 'A teenage girl risks everything when she falls in love with a vampire.', '2008-11-17 00:00:00');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `password`) VALUES
(1, 'pradeep@whiz-solutions.com', '$2b$10$84NyRDHX0swFHHuiluTxRevs3q33EhCiRIAjXnzUPSJ.TKGQhpPgm'),
(2, 'test@gmail.com', '$2b$10$bCKetkush9o7UlRRu0.Nue3Ygtz1yozGa.GpxKOD7MWIQy1eQyLBe');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `movies`
--
ALTER TABLE `movies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=211;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
